title: Blog
description: [IT文件]
#remote_theme: pages-themes/tactile@v0.2.0
#remote_theme: pages-themes/Cayman
#remote_theme: pages-themes/Hacker
#remote_theme: pages-themes/leap-day
#remote_theme: pages-themes/merlot
#remote_theme: pages-themes/midnight
#remote_theme: pages-themes/minima
#remote_theme: pages-themes/modernist
#remote_theme: pages-themes/slate
#remote_theme: pages-themes/minimal
remote_theme: pages-themes/time-machine
#remote_theme: riggraz/no-style-please
#remote_theme: cotes2020/jekyll-theme-chirpy
#remote_theme: just-the-docs/just-the-docs